# Generated by Django 3.2.20 on 2023-07-13 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230714_0036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IgHashtag',
        ),
    ]
