# Generated by Django 3.2.20 on 2023-07-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_ighashtag'),
        ('app', '0007_post_likes'),
    ]

    operations = [
    ]
