# Generated by Django 3.2.20 on 2023-07-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230715_1127'),
        ('app', '0008_merge_0006_delete_ighashtag_0007_post_likes'),
    ]

    operations = [
    ]
