# Generated by Django 3.2.20 on 2023-07-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_connection'),
        ('app', '0011_remove_customuser_following'),
    ]

    operations = [
    ]
